import "./globals.scss";
import type { Metadata } from "next";
import "react-material-symbols/outlined";
import { roboto } from "./fonts";

export const metadata: Metadata = {
  title: "Counter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
