import "./globals.scss";
import type { Metadata } from "next";
import { Inter, Roboto, Montserrat } from "next/font/google";
import "react-material-symbols/outlined";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
});
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Counter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classNames(
          inter.className,
          roboto.className,
          montserrat.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
